# Copyright 2026 Stephan Schultchen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import NamedTuple
from typing import Optional

V4 = "/pdb/query/v4"

PLACEHOLDERS = ("{node}", "{fact}", "{factvalue}", "{type}", "{environment}")


class Case(NamedTuple):
    name: str
    origin: str
    path: str
    query: Optional[list] = None
    params: Optional[dict] = None
    expect_error: bool = False


def _c(name, origin, path, query=None, params=None, expect_error=False) -> Case:
    return Case(name, origin, path, query, params or {}, expect_error)


ENDPOINTS = [
    _c("nodes", "integration", V4 + "/nodes", ["=", "certname", "{node}"]),
    _c("nodes single", "integration", V4 + "/nodes/{node}"),
    _c("nodes all", "integration", V4 + "/nodes"),
    _c("facts", "integration", V4 + "/facts", ["=", "certname", "{node}"]),
    _c("facts by path name", "integration", V4 + "/facts/{fact}"),
    _c("facts by path name and value", "integration",
       V4 + "/facts/{fact}/{factvalue}"),
    _c("fact-names", "integration", V4 + "/fact-names"),
    _c("fact-paths", "integration", V4 + "/fact-paths"),
    _c("fact-contents", "integration", V4 + "/fact-contents",
       ["=", "certname", "{node}"]),
    _c("factsets", "integration", V4 + "/factsets", ["=", "certname", "{node}"]),
    _c("inventory", "integration", V4 + "/inventory", ["=", "certname", "{node}"]),
    _c("resources", "integration", V4 + "/resources", ["=", "certname", "{node}"]),
    _c("resources by path type", "integration", V4 + "/resources/{type}",
       ["=", "certname", "{node}"]),
    _c("edges", "integration", V4 + "/edges", ["=", "certname", "{node}"]),
    _c("catalogs", "integration", V4 + "/catalogs", ["=", "certname", "{node}"]),
    _c("catalogs single", "integration", V4 + "/catalogs/{node}"),
    _c("catalogs edges href", "conformance", V4 + "/catalogs/{node}/edges",
       ["=", "certname", "{node}"]),
    _c("catalogs resources href", "conformance", V4 + "/catalogs/{node}/resources"),
    _c("catalog-inputs", "integration", V4 + "/catalog-inputs"),
    _c("catalog-input-contents", "integration", V4 + "/catalog-input-contents"),
    _c("packages", "integration", V4 + "/packages"),
    _c("package-inventory", "integration", V4 + "/package-inventory"),
    _c("reports", "integration", V4 + "/reports", ["=", "certname", "{node}"]),
    _c("events", "integration", V4 + "/events", ["=", "certname", "{node}"]),
    _c("environments", "integration", V4 + "/environments"),
    _c("environments single", "integration", V4 + "/environments/{environment}"),
    _c("producers", "integration", V4 + "/producers"),
    _c("node facts", "integration", V4 + "/nodes/{node}/facts"),
    _c("node resources", "integration", V4 + "/nodes/{node}/resources"),
    _c("environment facts", "integration",
       V4 + "/environments/{environment}/facts", ["=", "certname", "{node}"]),
    _c("environment resources", "integration",
       V4 + "/environments/{environment}/resources", ["=", "certname", "{node}"]),
    _c("environment reports", "integration",
       V4 + "/environments/{environment}/reports", ["=", "certname", "{node}"]),
    _c("environment events", "integration",
       V4 + "/environments/{environment}/events", ["=", "certname", "{node}"]),
]

FILTERS = [
    _c("nodes fact field form", "integration", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"],
        ["=", ["fact", "{fact}"], "{factvalue}"]]),
    _c("nodes node_state active", "integration", V4 + "/nodes",
       ["=", "node_state", "active"]),
    _c("nodes node active form", "unit", V4 + "/nodes",
       ["=", ["node", "active"], True]),
    _c("nodes node_state inactive", "integration", V4 + "/nodes",
       ["=", "node_state", "inactive"]),
    _c("nodes certname regex", "unit", V4 + "/nodes", ["~", "certname", "."]),
    _c("nodes environment", "unit", V4 + "/nodes",
       ["=", "catalog_environment", "{environment}"]),
    _c("nodes latest_report_status", "unit", V4 + "/nodes",
       ["=", "latest_report_status", "unchanged"]),
    _c("facts by name", "integration", V4 + "/facts", ["=", "name", "{fact}"]),
    _c("facts pinned name vs regex", "integration", V4 + "/facts",
       ["and", ["=", "certname", "{node}"], ["~", "name", "^{fact}$"]]),
    _c("facts absent name", "integration", V4 + "/facts",
       ["=", "name", "definitely_not_a_fact"]),
    _c("facts name in array", "integration", V4 + "/facts",
       ["and", ["=", "certname", "{node}"],
        ["in", "name", ["array", ["{fact}", "clientcert"]]]]),
    _c("facts name and value", "integration", V4 + "/facts",
       ["and", ["=", "certname", "{node}"], ["=", "name", "{fact}"],
        ["=", "value", "{factvalue}"]]),
    _c("facts value regex", "unit", V4 + "/facts",
       ["and", ["=", "name", "{fact}"], ["~", "value", "."]]),
    _c("facts environment", "unit", V4 + "/facts",
       ["and", ["=", "name", "{fact}"], ["=", "environment", "{environment}"]]),
    _c("inventory dotted fact", "integration", V4 + "/inventory",
       ["=", "facts.{fact}", "{factvalue}"]),
    _c("inventory trusted", "unit", V4 + "/inventory",
       ["=", "trusted.certname", "{node}"]),
    _c("fact-contents by name", "integration", V4 + "/fact-contents",
       ["and", ["=", "certname", "{node}"], ["=", "name", "{fact}"]]),
    _c("fact-contents path equals", "integration", V4 + "/fact-contents",
       ["and", ["=", "certname", "{node}"], ["=", "path", ["{fact}"]]]),
    _c("fact-contents regex array", "unit", V4 + "/fact-contents",
       ["and", ["=", "certname", "{node}"], ["~>", "path", ["{fact}"]]]),
    _c("fact-contents regex array wildcard", "unit", V4 + "/fact-contents",
       ["~>", "path", ["networking", ".*"]]),
    _c("fact-paths regex array", "unit", V4 + "/fact-paths",
       ["~>", "path", ["{fact}"]]),
    _c("fact-paths regex array index", "review", V4 + "/fact-paths",
       ["~>", "path", ["networking", ".*", "0"]]),
    _c("fact-paths by name", "unit", V4 + "/fact-paths", ["=", "name", "{fact}"]),
    _c("fact-paths by type", "unit", V4 + "/fact-paths",
       ["=", "type", "string"]),
    _c("resources by type", "integration", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["=", "type", "{type}"]]),
    _c("resources dotted parameter", "integration", V4 + "/resources",
       ["and", ["=", "certname", "{node}"],
        ["=", "parameters.ensure", "present"]]),
    _c("resources parameter form", "integration", V4 + "/resources",
       ["and", ["=", "certname", "{node}"],
        ["=", ["parameter", "ensure"], "present"]]),
    _c("resources tag filter", "integration", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["=", "tag", "class"]]),
    _c("resources exported true", "integration", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["=", "exported", True]]),
    _c("resources exported false", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["=", "exported", False]]),
    _c("resources title regex", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["~", "title", "^/"]]),
    _c("resources line greater", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], [">", "line", 1]]),
    _c("resources line null true", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["null?", "line", True]]),
    _c("resources line null false", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["null?", "line", False]]),
    _c("resources not type", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"], ["not", ["=", "type", "{type}"]]]),
    _c("resources or types", "unit", V4 + "/resources",
       ["and", ["=", "certname", "{node}"],
        ["or", ["=", "type", "{type}"], ["=", "type", "Class"]]]),
    _c("edges relationship", "unit", V4 + "/edges",
       ["and", ["=", "certname", "{node}"], ["=", "relationship", "contains"]]),
    _c("catalogs code_id null", "unit", V4 + "/catalogs",
       ["and", ["=", "certname", "{node}"], ["null?", "code_id", True]]),
    _c("reports by status", "integration", V4 + "/reports",
       ["=", "status", "unchanged"]),
    _c("reports latest only", "unit", V4 + "/reports",
       ["and", ["=", "certname", "{node}"], ["=", "latest_report?", True]]),
    _c("reports noop false", "unit", V4 + "/reports",
       ["and", ["=", "certname", "{node}"], ["=", "noop", False]]),
    _c("reports environment", "unit", V4 + "/reports",
       ["=", "environment", "{environment}"]),
    _c("reports node_state", "review", V4 + "/reports",
       ["and", ["=", "certname", "{node}"], ["=", "node_state", "active"]]),
    _c("events by status", "integration", V4 + "/events",
       ["and", ["=", "certname", "{node}"], ["=", "status", "success"]]),
    _c("events latest only", "unit", V4 + "/events",
       ["and", ["=", "certname", "{node}"], ["=", "latest_report?", True]]),
    _c("events containing_class not null", "unit", V4 + "/events",
       ["and", ["=", "certname", "{node}"],
        ["null?", "containing_class", False]]),
    _c("events node_state", "review", V4 + "/events",
       ["and", ["=", "certname", "{node}"], ["=", "node_state", "active"]]),
]

TIMESTAMPS = [
    _c("nodes catalog_timestamp gte", "integration", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"],
        [">=", "catalog_timestamp", "2000-01-01T00:00:00Z"]]),
    _c("nodes catalog_timestamp lt", "integration", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"],
        ["<", "catalog_timestamp", "2000-01-01T00:00:00Z"]]),
    _c("nodes report_timestamp gte", "review", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"],
        [">=", "report_timestamp", "2000-01-01T00:00:00Z"]]),
    _c("nodes report_timestamp lt future", "review", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"],
        ["<", "report_timestamp", "2100-01-01T00:00:00Z"]]),
    _c("nodes report_timestamp range", "review", V4 + "/nodes",
       ["and", [">=", "report_timestamp", "2000-01-01T00:00:00Z"],
        ["<", "report_timestamp", "2100-01-01T00:00:00Z"]]),
    _c("nodes facts_timestamp gte", "unit", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"],
        [">=", "facts_timestamp", "2000-01-01T00:00:00Z"]]),
    _c("nodes expired null", "integration", V4 + "/nodes",
       ["and", ["=", "certname", "{node}"], ["null?", "expired", True]]),
    _c("reports end_time gte", "integration", V4 + "/reports",
       ["and", ["=", "certname", "{node}"],
        [">=", "end_time", "2000-01-01T00:00:00Z"]]),
    _c("reports start_time lte", "unit", V4 + "/reports",
       ["and", ["=", "certname", "{node}"],
        ["<=", "start_time", "2100-01-01T00:00:00Z"]]),
    _c("reports producer_timestamp gte", "unit", V4 + "/reports",
       ["and", ["=", "certname", "{node}"],
        [">=", "producer_timestamp", "2000-01-01T00:00:00Z"]]),
    _c("events timestamp gte", "unit", V4 + "/events",
       ["and", ["=", "certname", "{node}"],
        [">=", "timestamp", "2000-01-01T00:00:00Z"]]),
]

PROJECTION = [
    _c("extract two columns", "integration", V4 + "/reports",
       ["extract", ["certname", "status"], ["=", "certname", "{node}"]]),
    _c("extract single string column", "unit", V4 + "/nodes",
       ["extract", "certname", ["=", "certname", "{node}"]]),
    _c("extract node report fields", "conformance", V4 + "/nodes",
       ["extract", ["certname", "latest_report_status"],
        ["=", "certname", "{node}"]]),
    _c("count nodes", "integration", V4,
       ["from", "nodes", ["extract", [["function", "count"]]]]),
    _c("count resources group_by type", "integration", V4,
       ["from", "resources",
        ["extract", [["function", "count"], "type"],
         ["=", "certname", "{node}"], ["group_by", "type"]]]),
    _c("count facts group_by value", "integration", V4,
       ["from", "facts",
        ["extract", ["value", ["function", "count"]],
         ["=", "name", "{fact}"], ["group_by", "value"]]]),
    _c("count reports group_by certname", "conformance", V4,
       ["from", "reports",
        ["extract", [["function", "count"], "certname"],
         ["group_by", "certname"]]]),
    _c("min max end_time", "unit", V4,
       ["from", "reports",
        ["extract", [["function", "min", "end_time"],
                     ["function", "max", "end_time"]],
         ["=", "certname", "{node}"]]]),
    _c("avg line", "unit", V4,
       ["from", "resources",
        ["extract", [["function", "avg", "line"]],
         ["=", "certname", "{node}"]]]),
    _c("count environments", "unit", V4,
       ["from", "environments", ["extract", [["function", "count"]]]]),
]

PAGING = [
    _c("limit and order_by asc", "integration", V4 + "/nodes", None,
       {"limit": "5", "order_by": '[{"field":"certname","order":"asc"}]'}),
    _c("limit order_by include_total", "integration", V4 + "/resources",
       ["=", "certname", "{node}"],
       {"limit": "1", "include_total": "true",
        "order_by": '[{"field":"type","order":"asc"}]'}),
    _c("include_total without limit", "review", V4 + "/nodes", None,
       {"include_total": "true"}),
    _c("order_by desc timestamp", "integration", V4 + "/nodes", None,
       {"limit": "5",
        "order_by": '[{"field":"catalog_timestamp","order":"desc"}]'}),
    _c("offset", "unit", V4 + "/nodes", None,
       {"limit": "2", "offset": "1",
        "order_by": '[{"field":"certname","order":"asc"}]'}),
    _c("ast limit and order_by", "unit", V4,
       ["from", "nodes", ["limit", 3], ["order_by", [["certname", "asc"]]]]),
    _c("ast offset", "unit", V4,
       ["from", "nodes", ["limit", 2], ["offset", 1],
        ["order_by", [["certname", "asc"]]]]),
    _c("order_by two fields", "unit", V4 + "/resources",
       ["=", "certname", "{node}"],
       {"limit": "20",
        "order_by": '[{"field":"type","order":"asc"},'
                    '{"field":"title","order":"desc"}]'}),
]

SUBQUERIES = [
    _c("in select_facts", "integration", V4 + "/resources",
       ["and", ["=", "type", "{type}"],
        ["in", "certname",
         ["extract", "certname",
          ["select_facts", ["and", ["=", "name", "{fact}"],
                            ["=", "value", "{factvalue}"]]]]]]),
    _c("in select_resources", "unit", V4 + "/nodes",
       ["in", "certname",
        ["extract", "certname",
         ["select_resources", ["=", "type", "{type}"]]]]),
    _c("not in select_facts", "unit", V4 + "/nodes",
       ["not", ["in", "certname",
                ["extract", "certname",
                 ["select_facts",
                  ["=", "name", "definitely_not_a_fact"]]]]]),
    _c("subquery operator", "conformance", V4 + "/facts",
       ["and", ["=", "certname", "{node}"],
        ["subquery", "resources", ["=", "type", "{type}"]]]),
    _c("in from-style subquery", "conformance", V4 + "/nodes",
       ["in", "certname",
        ["from", "facts", ["extract", ["certname"], ["=", "name", "{fact}"]]]]),
    _c("two column in", "conformance", V4 + "/facts",
       ["in", ["certname", "environment"],
        ["extract", ["certname", "environment"],
         ["select_facts", ["=", "name", "{fact}"]]]]),
    _c("nested subquery depth 2", "conformance", V4 + "/resources",
       ["in", "certname",
        ["extract", "certname",
         ["select_facts",
          ["and", ["=", "name", "{fact}"],
           ["in", "certname",
            ["extract", "certname",
             ["select_resources", ["=", "type", "{type}"]]]]]]]]),
    _c("events in select_resources", "conformance", V4 + "/events",
       ["in", "certname",
        ["extract", "certname",
         ["select_resources", ["=", "type", "{type}"]]]]),
    _c("reports in select_nodes", "review", V4 + "/reports",
       ["in", "certname",
        ["extract", "certname",
         ["select_nodes", ["=", "node_state", "active"]]]]),
]

UPSTREAM_ROUTES = [
    _c("node facts by name", "conformance", V4 + "/nodes/{node}/facts/{fact}"),
    _c("node facts by name and value", "conformance",
       V4 + "/nodes/{node}/facts/{fact}/{factvalue}"),
    _c("node resources by type", "conformance", V4 + "/nodes/{node}/resources/{type}"),
    _c("environment facts by name", "conformance",
       V4 + "/environments/{environment}/facts/{fact}"),
    _c("environment resources by type", "conformance",
       V4 + "/environments/{environment}/resources/{type}",
       ["=", "certname", "{node}"]),
    _c("environment report events", "conformance",
       V4 + "/environments/{environment}/reports/{hash}/events"),
    _c("report metrics", "conformance", V4 + "/reports/{hash}/metrics"),
    _c("report logs", "conformance", V4 + "/reports/{hash}/logs"),
    _c("producer factsets", "conformance", V4 + "/producers/{producer}/factsets",
       ["=", "certname", "{node}"]),
    _c("producer catalogs", "conformance", V4 + "/producers/{producer}/catalogs",
       ["=", "certname", "{node}"]),
    _c("producer reports", "conformance", V4 + "/producers/{producer}/reports",
       ["=", "certname", "{node}"]),
    _c("producer catalog edges cannot filter by producer", "conformance",
       V4 + "/producers/{producer}/catalogs/{node}/edges", expect_error=True),
    _c("factset single", "conformance", V4 + "/factsets/{node}"),
    _c("factset facts", "conformance", V4 + "/factsets/{node}/facts"),
    _c("package inventory of node", "conformance", V4 + "/package-inventory/{node}"),
    _c("catalog resources by type", "conformance",
       V4 + "/catalogs/{node}/resources/{type}"),
    _c("catalog resources by type and title", "conformance",
       V4 + "/catalogs/{node}/resources/Class/Bench::Config"),
    _c("unknown node child route is 404", "conformance",
       V4 + "/nodes/no-such-node.example.com/facts", expect_error=True),
    _c("unknown report child route is 404", "conformance",
       V4 + "/reports/0000000000000000000000000000000000000000/events", expect_error=True),
    _c("unknown environment is 404", "conformance",
       V4 + "/environments/no-such-env", expect_error=True),
    _c("unknown factset is 404", "conformance", V4 + "/factsets/no-such-node",
       expect_error=True),
    _c("unsupported query parameter", "conformance", V4 + "/nodes",
       ["=", "certname", "{node}"], {"bogus": "1"}, expect_error=True),
    _c("root without query", "conformance", V4, expect_error=True),
    _c("aggregate-event-counts rejects paging", "conformance",
       V4 + "/aggregate-event-counts", ["=", "certname", "{node}"],
       {"summarize_by": "certname", "limit": "1"}, expect_error=True),
    _c("distinct_resources without window", "conformance", V4 + "/events",
       ["=", "certname", "{node}"], {"distinct_resources": "true"}, expect_error=True),
    _c("retired v3 api", "conformance", "/pdb/query/v3/nodes", expect_error=True),
    _c("pretty output", "conformance", V4 + "/nodes/{node}", None, {"pretty": "true"}),
    _c("float timeout", "conformance", V4 + "/nodes/{node}", None, {"timeout": "2.5"}),
    _c("ast_only echoes the query", "conformance", V4,
       ["from", "nodes", ["=", "certname", "{node}"]], {"ast_only": "true"}),
    _c("include_facts_expiration", "conformance", V4 + "/nodes/{node}", None,
       {"include_facts_expiration": "true"}),
    _c("include_package_inventory", "conformance", V4 + "/factsets/{node}", None,
       {"include_package_inventory": "true"}),
    _c("distinct events", "conformance", V4 + "/events", ["=", "certname", "{node}"],
       {"distinct_resources": "true", "distinct_start_time": "2026-09-22T00:00:00Z",
        "distinct_end_time": "2026-09-23T00:00:00Z"}),
    _c("distinct event-counts", "conformance", V4 + "/event-counts",
       ["=", "certname", "{node}"],
       {"summarize_by": "resource", "distinct_resources": "true",
        "distinct_start_time": "2026-09-22T00:00:00Z",
        "distinct_end_time": "2026-09-23T00:00:00Z"}),
    _c("deactivated nodes are hidden by default", "conformance", V4 + "/nodes",
       ["=", "node_state", "inactive"]),
]

EVENT_COUNTS = [
    _c("event-counts certname", "integration", V4 + "/event-counts",
       ["=", "certname", "{node}"], {"summarize_by": "certname"}),
    _c("event-counts resource", "integration", V4 + "/event-counts",
       ["=", "certname", "{node}"], {"summarize_by": "resource"}),
    _c("event-counts containing_class", "unit", V4 + "/event-counts",
       ["=", "certname", "{node}"], {"summarize_by": "containing_class"}),
    _c("event-counts count_by certname", "unit", V4 + "/event-counts",
       ["=", "certname", "{node}"],
       {"summarize_by": "resource", "count_by": "certname"}),
    _c("event-counts counts_filter", "conformance", V4 + "/event-counts",
       ["=", "certname", "{node}"],
       {"summarize_by": "certname", "counts_filter": '[">","successes",0]'}),
    _c("event-counts all nodes", "unit", V4 + "/event-counts",
       ["=", "status", "success"], {"summarize_by": "certname"}),
    _c("aggregate-event-counts certname", "integration",
       V4 + "/aggregate-event-counts", ["=", "certname", "{node}"],
       {"summarize_by": "certname"}),
    _c("aggregate-event-counts resource", "unit",
       V4 + "/aggregate-event-counts", ["=", "certname", "{node}"],
       {"summarize_by": "resource"}),
    _c("aggregate-event-counts status filter", "conformance",
       V4 + "/aggregate-event-counts",
       ["or", ["=", "status", "success"], ["=", "status", "skipped"]],
       {"summarize_by": "certname"}),
]

ROOT = [
    _c("root from nodes", "integration", V4,
       ["from", "nodes", ["=", "certname", "{node}"]]),
    _c("root from facts", "unit", V4,
       ["from", "facts", ["=", "certname", "{node}"]]),
    _c("root from reports limit", "unit", V4,
       ["from", "reports", ["=", "certname", "{node}"],
        ["order_by", [["receive_time", "desc"]]], ["limit", 1]]),
    _c("root from environments", "unit", V4, ["from", "environments"]),
]

ERRORS = [
    _c("unknown field", "integration", V4 + "/resources",
       ["=", "sourcefile", "/x"], expect_error=True),
    _c("unknown entity", "unit", V4, ["from", "nope"], expect_error=True),
    _c("empty and", "review", V4 + "/nodes", ["and"], expect_error=True),
    _c("empty or", "review", V4 + "/nodes", ["or"], expect_error=True),
    _c("not without argument", "review", V4 + "/nodes",
       ["not"], expect_error=True),
    _c("not with two arguments", "review", V4 + "/nodes",
       ["not", ["=", "certname", "a"], ["=", "certname", "b"]],
       expect_error=True),
    _c("binary operator arity", "conformance", V4 + "/nodes",
       ["=", "certname"], expect_error=True),
    _c("regex array on non path field", "review", V4 + "/facts",
       ["~>", "name", ["os"]], expect_error=True),
    _c("invalid regex", "unit", V4 + "/nodes",
       ["~", "certname", "["], expect_error=True),
    _c("unknown operator", "unit", V4 + "/nodes",
       ["nope", "certname", "a"], expect_error=True),
    _c("bad order direction", "unit", V4 + "/nodes", None,
       {"order_by": '[{"field":"certname","order":"sideways"}]'},
       expect_error=True),
    _c("extract unknown column", "unit", V4 + "/nodes",
       ["extract", ["nope"]], expect_error=True),
    _c("event-counts without summarize_by", "unit", V4 + "/event-counts",
       ["=", "certname", "{node}"], expect_error=True),
    _c("event-counts bad summarize_by", "unit", V4 + "/event-counts",
       ["=", "certname", "{node}"], {"summarize_by": "nope"},
       expect_error=True),
]

DIVERGENCES = [
    _c("event-counts count_by certname per certname "
       "(upstream: corrective_change is always null, so its distinct rows collapse)",
       "divergence", V4 + "/event-counts", ["=", "certname", "{node}"],
       {"summarize_by": "certname", "count_by": "certname"}),
    _c("environment report metrics "
       "(upstream: HTTP 400, PGobject error on the environment child route)",
       "divergence", V4 + "/environments/{environment}/reports/{hash}/metrics"),
    _c("report events href with paging "
       "(upstream: HTTP 500, schema error when order_by is given)",
       "divergence", V4 + "/reports/{hash}/events"),

    _c("subquery facts from resources "
       "(upstream: no implicit relationship)",
       "divergence", V4 + "/resources",
       ["and", ["=", "certname", "{node}"],
        ["subquery", "facts", ["=", "name", "{fact}"]]], expect_error=True),
    _c("extract wrapping from "
       "(upstream: unrecognized AST clause)",
       "divergence", V4 + "/nodes",
       ["in", "certname",
        ["extract", "certname", ["from", "facts", ["=", "name", "{fact}"]]]],
       expect_error=True),
    _c("fact_names underscore alias "
       "(upstream: schema error, HTTP 500)",
       "divergence", V4, ["from", "fact_names"], expect_error=True),
    _c("packages certname column "
       "(upstream: not a queryable object for packages)",
       "divergence", V4 + "/packages", ["=", "certname", "{node}"],
       expect_error=True),
    _c("node reports sub-route does not exist", "conformance",
       V4 + "/nodes/{node}/reports", expect_error=True),
    _c("node events sub-route does not exist", "conformance",
       V4 + "/nodes/{node}/events", expect_error=True),
    _c("root from producers "
       "(upstream: schema error, HTTP 500)",
       "divergence", V4, ["from", "producers"], expect_error=True),
    _c("root from fact-names "
       "(upstream: schema error, HTTP 500)",
       "divergence", V4, ["from", "fact-names"], expect_error=True),
    _c("zero limit "
       "(upstream: HTTP 500, pyppetdb answers 400)",
       "divergence", V4, ["from", "nodes", ["limit", 0]], expect_error=True),
]

GROUPS = {
    "endpoints": ENDPOINTS,
    "filters": FILTERS,
    "timestamps": TIMESTAMPS,
    "projection": PROJECTION,
    "paging": PAGING,
    "subqueries": SUBQUERIES,
    "event_counts": EVENT_COUNTS,
    "upstream_routes": UPSTREAM_ROUTES,
    "root": ROOT,
    "errors": ERRORS,
}

CASES = [case for group in GROUPS.values() for case in group]
GROUPS["divergences"] = DIVERGENCES
