site_name: pyppetdb
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.integrate

nav:
  - Introduction: index.md
  - Architecture: architecture.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Nodes: nodes.md
  - Hiera: hiera.md
  - Administration: administration.md
  - CA: ca.md
  - Jobs: jobs.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
